import { generateId } from './ids';
import { Keys, ModelRef, JudgeEvaluation, ProviderId } from './storage';
import { getProvider } from '../providers';
import { ChatMsg } from '../providers/types';

export const DEFAULT_JUDGE_MODELS: Record<ProviderId, ModelRef> = {
  openai: { provider: 'openai', id: 'gpt-4o', label: 'GPT-4o' },
  gemini: { provider: 'gemini', id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
  anthropic: { provider: 'anthropic', id: 'claude-3-5-sonnet-20241022', label: 'Claude 3.5 Sonnet' },
  xai: { provider: 'xai', id: 'grok-2-latest', label: 'Grok 2' },
};

export const FALLBACK_SECONDARY_MODELS: Record<ProviderId, ModelRef> = {
  openai: { provider: 'openai', id: 'gpt-4o-mini', label: 'GPT-4o Mini' },
  gemini: { provider: 'gemini', id: 'gemini-1.5-flash', label: 'Gemini 1.5 Flash' },
  anthropic: { provider: 'anthropic', id: 'claude-3-5-haiku-20241022', label: 'Claude 3.5 Haiku' },
  xai: { provider: 'xai', id: 'grok-beta', label: 'Grok Beta' },
};

/**
 * Automatically picks an independent Judge model.
 * Prioritizes a different company/provider from the evaluated model.
 */
export function pickJudgeModel(
  evaluatedModel: ModelRef | undefined,
  keys: Keys,
  preferred?: ModelRef | null
): ModelRef | null {
  // If user explicitly picked a preferred judge model and has its key, use it (unless identical to evaluated)
  if (preferred && keys[preferred.provider]) {
    if (!evaluatedModel || preferred.provider !== evaluatedModel.provider || preferred.id !== evaluatedModel.id) {
      return preferred;
    }
  }

  const evalProvider = evaluatedModel?.provider;
  const availableProviders = (['gemini', 'openai', 'anthropic', 'xai'] as ProviderId[]).filter(
    (p) => !!keys[p]
  );

  if (availableProviders.length === 0) return null;

  // Try to find a different provider
  const differentProviders = availableProviders.filter((p) => p !== evalProvider);

  if (differentProviders.length > 0) {
    const chosenProvider = differentProviders[0];
    return DEFAULT_JUDGE_MODELS[chosenProvider];
  }

  // Same provider fallback: pick secondary model
  if (evalProvider && keys[evalProvider]) {
    if (evaluatedModel?.id === DEFAULT_JUDGE_MODELS[evalProvider].id) {
      return FALLBACK_SECONDARY_MODELS[evalProvider];
    }
    return DEFAULT_JUDGE_MODELS[evalProvider];
  }

  return null;
}

export interface EvaluateArgs {
  userQuery: string;
  assistantResponse: string;
  retrievedContext?: string;
  evaluatedModel?: ModelRef;
  judgeModel: ModelRef;
  key: string;
  signal?: AbortSignal;
}

export async function evaluateResponse(args: EvaluateArgs): Promise<JudgeEvaluation> {
  const {
    userQuery,
    assistantResponse,
    retrievedContext,
    evaluatedModel,
    judgeModel,
    key,
    signal,
  } = args;

  const system = `You are an impartial, highly rigorous AI evaluator acting as an LLM Judge.
Your objective is to evaluate the quality, factual accuracy, completeness, and clarity of an AI response to a user prompt.
Be discerning, balanced, and constructively critical.

Output your judgment as strict JSON adhering to this exact schema:
{
  "overallScore": <integer between 0 and 100>,
  "accuracyScore": <integer between 1 and 10>,
  "completenessScore": <integer between 1 and 10>,
  "clarityScore": <integer between 1 and 10>,
  "hallucinationRisk": "low" | "medium" | "high",
  "verdict": "Accurate & Reliable" | "Minor Issues / Incomplete" | "Questionable / Inaccurate",
  "summary": "<1-2 sentence overall evaluation assessment>",
  "strengths": ["<strength 1>", "<strength 2>"],
  "weaknesses": ["<weakness 1>", "<weakness 2>"],
  "suggestedCorrections": "<specific factual corrections or key missing information, or null if none>"
}
Ensure output is ONLY valid JSON, without surrounding chit-chat.`;

  let prompt = `[USER QUERY]\n${userQuery}\n\n`;
  if (retrievedContext && retrievedContext.trim()) {
    prompt += `[GROUNDING CONTEXT (Web / Docs)]\n${retrievedContext.slice(0, 8000)}\n\n`;
  }
  prompt += `[RESPONSE TO EVALUATE]\n(Generated by ${evaluatedModel?.label || evaluatedModel?.id || 'Assistant'})\n${assistantResponse}\n\n`;
  prompt += `Evaluate the response now and return the JSON assessment:`;

  const messages: ChatMsg[] = [{ role: 'user', text: prompt }];

  const adapter = getProvider(judgeModel.provider);
  let accumulated = '';

  await adapter.chat({
    model: judgeModel.id,
    system,
    messages,
    temperature: 0.2, // Low temperature for consistent grading
    key,
    signal: signal || new AbortController().signal,
    onText: (delta) => {
      accumulated += delta;
    },
  });

  // Extract JSON from response
  const parsed = extractJudgeJson(accumulated);

  return {
    id: generateId('judge'),
    judgeModel,
    evaluatedAt: Date.now(),
    overallScore: clamp(parsed.overallScore ?? 80, 0, 100),
    accuracyScore: clamp(parsed.accuracyScore ?? 8, 1, 10),
    completenessScore: clamp(parsed.completenessScore ?? 8, 1, 10),
    clarityScore: clamp(parsed.clarityScore ?? 8, 1, 10),
    hallucinationRisk: validateRisk(parsed.hallucinationRisk),
    verdict: validateVerdict(parsed.verdict, parsed.overallScore ?? 80),
    summary: parsed.summary || 'Evaluation completed.',
    strengths: Array.isArray(parsed.strengths) && parsed.strengths.length > 0
      ? parsed.strengths.slice(0, 4)
      : ['Clear presentation of ideas', 'Directly addressed the query'],
    weaknesses: Array.isArray(parsed.weaknesses) && parsed.weaknesses.length > 0
      ? parsed.weaknesses.slice(0, 4)
      : ['Could provide deeper nuance or examples'],
    suggestedCorrections: parsed.suggestedCorrections || undefined,
    status: 'done',
  };
}

function extractJudgeJson(raw: string): any {
  // Check for ```json ... ```
  const match = raw.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
  const textToParse = match ? match[1] : raw;

  // Try finding outermost JSON object
  const start = textToParse.indexOf('{');
  const end = textToParse.lastIndexOf('}');
  if (start !== -1 && end !== -1 && end > start) {
    try {
      return JSON.parse(textToParse.slice(start, end + 1));
    } catch {
      // Lenient recovery
    }
  }

  try {
    return JSON.parse(textToParse);
  } catch {
    return {};
  }
}

function clamp(val: number, min: number, max: number): number {
  if (isNaN(val)) return min;
  return Math.min(Math.max(Math.round(val), min), max);
}

function validateRisk(val: any): 'low' | 'medium' | 'high' {
  if (val === 'low' || val === 'medium' || val === 'high') return val;
  return 'low';
}

function validateVerdict(
  verdict: any,
  score: number
): 'Accurate & Reliable' | 'Minor Issues / Incomplete' | 'Questionable / Inaccurate' {
  if (
    verdict === 'Accurate & Reliable' ||
    verdict === 'Minor Issues / Incomplete' ||
    verdict === 'Questionable / Inaccurate'
  ) {
    return verdict;
  }
  if (score >= 85) return 'Accurate & Reliable';
  if (score >= 65) return 'Minor Issues / Incomplete';
  return 'Questionable / Inaccurate';
}
